ecommerce:
  outputs:
    dev:
      type: snowflake
      account: BGUQBGY-RP01589
      user: SAAD
      password: Chintapakdumdum
      role: ACCOUNTADMIN
      database: ecommerce_db
      warehouse: COMPUTE_WH
      schema: analysis
      threads: 1
      client_session_keep_alive: False
  target: dev
